org: moullxndev
service: rbac-cognito

provider:
  name: aws
  runtime: nodejs22.x
  architecture: arm64
  region: us-east-1
  environment:
    COGNITO_CLIENT_ID: !Ref UserPoolClient

package:
  individually: true

build:
  esbuild:
    minify: true
    bundle: true
    sourcemap: false

functions:
  signup:
    handler: src/functions/auth/signup.handler
    events:
      - httpApi:
          path: /auth/signup
          method: POST
  confirmSignup:
    handler: src/functions/auth/confirmSignup.handler
    events:
      - httpApi:
          path: /auth/confirm-signup
          method: POST

resources:
  Resources:
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: rbac-cognito
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
        MfaConfiguration: OFF
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        Schema:
          - Name: email
            Required: true
            Mutable: true
          - Name: given_name
            Required: true
            Mutable: true
    UserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: UserPoolClient
        UserPoolId: !Ref UserPool
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
