org: moullxndev
service: rbac-cognito

provider:
  name: aws
  runtime: nodejs22.x
  architecture: arm64
  region: us-east-1
  environment:
    COGNITO_CLIENT_ID: !Ref UserPoolClient
  httpApi:
    authorizers:
      CognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: !GetAtt UserPool.ProviderURL
        audience:
          - !Ref UserPoolClient

package:
  individually: true

build:
  esbuild:
    minify: true
    bundle: true
    sourcemap: false

functions:
  signup:
    handler: src/functions/auth/signup.handler
    events:
      - httpApi:
          path: /auth/signup
          method: POST
  confirmSignup:
    handler: src/functions/auth/confirmSignup.handler
    events:
      - httpApi:
          path: /auth/confirm-signup
          method: POST
  signin:
    handler: src/functions/auth/signin.handler
    events:
      - httpApi:
          path: /auth/signin
          method: POST
  createLesson:
    handler: src/functions/lessons/createLesson.handler
    events:
      - httpApi:
          path: /lessons
          method: POST
          authorizer:
            name: CognitoAuthorizer

resources:
  Resources:
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: rbac-cognito
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
        MfaConfiguration: OFF
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        Schema:
          - Name: email
            Required: true
            Mutable: true
          - Name: given_name
            Required: true
            Mutable: true
          - Name: role
            Mutable: true
            AttributeDataType: String
    UserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: UserPoolClient
        UserPoolId: !Ref UserPool
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
