org: moullxndev
service: rbac-cognito

provider: ${file(./sls/provider.yml)}

package:
  individually: true

build: ${file(./sls/esbuild.yml)}

functions:
  - ${file(./sls/functions/auth.yml)}
  - ${file(./sls/functions/lessons.yml)}
  - ${file(./sls/functions/roles.yml)}

resources:
  - ${file(./sls/resources/cognito.yml)}
